/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { VoiceAssistant } from "./VoiceAssistant";
import { VoiceAssistantCountArgs } from "./VoiceAssistantCountArgs";
import { VoiceAssistantFindManyArgs } from "./VoiceAssistantFindManyArgs";
import { VoiceAssistantFindUniqueArgs } from "./VoiceAssistantFindUniqueArgs";
import { DeleteVoiceAssistantArgs } from "./DeleteVoiceAssistantArgs";
import { VoiceAssistantService } from "../voiceAssistant.service";
@graphql.Resolver(() => VoiceAssistant)
export class VoiceAssistantResolverBase {
  constructor(protected readonly service: VoiceAssistantService) {}

  async _voiceAssistantsMeta(
    @graphql.Args() args: VoiceAssistantCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [VoiceAssistant])
  async voiceAssistants(
    @graphql.Args() args: VoiceAssistantFindManyArgs
  ): Promise<VoiceAssistant[]> {
    return this.service.voiceAssistants(args);
  }

  @graphql.Query(() => VoiceAssistant, { nullable: true })
  async voiceAssistant(
    @graphql.Args() args: VoiceAssistantFindUniqueArgs
  ): Promise<VoiceAssistant | null> {
    const result = await this.service.voiceAssistant(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VoiceAssistant)
  async deleteVoiceAssistant(
    @graphql.Args() args: DeleteVoiceAssistantArgs
  ): Promise<VoiceAssistant | null> {
    try {
      return await this.service.deleteVoiceAssistant(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
