/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PostCallAction } from "./PostCallAction";
import { PostCallActionCountArgs } from "./PostCallActionCountArgs";
import { PostCallActionFindManyArgs } from "./PostCallActionFindManyArgs";
import { PostCallActionFindUniqueArgs } from "./PostCallActionFindUniqueArgs";
import { DeletePostCallActionArgs } from "./DeletePostCallActionArgs";
import { PostCallActionService } from "../postCallAction.service";
@graphql.Resolver(() => PostCallAction)
export class PostCallActionResolverBase {
  constructor(protected readonly service: PostCallActionService) {}

  async _postCallActionsMeta(
    @graphql.Args() args: PostCallActionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PostCallAction])
  async postCallActions(
    @graphql.Args() args: PostCallActionFindManyArgs
  ): Promise<PostCallAction[]> {
    return this.service.postCallActions(args);
  }

  @graphql.Query(() => PostCallAction, { nullable: true })
  async postCallAction(
    @graphql.Args() args: PostCallActionFindUniqueArgs
  ): Promise<PostCallAction | null> {
    const result = await this.service.postCallAction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PostCallAction)
  async deletePostCallAction(
    @graphql.Args() args: DeletePostCallActionArgs
  ): Promise<PostCallAction | null> {
    try {
      return await this.service.deletePostCallAction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
